replicaCount: 1

image:
  repository: 195690311722.dkr.ecr.eu-north-1.amazonaws.com/js-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 3001

ingress:
  enabled: false
